version: "3.3"
services:
  client:
    image: orqa/orqa_image_grading_client:latest
    build: 
      context: ./orqa_image_grading_client
      args:
        - "--configuration production"
    restart: unless-stopped
    ports:
      - "4200:80"
      - "4433:443"
    tty: true
    depends_on:
      - server
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks: 
      - orqa
  server:
    image: orqa/orqa-image-grading-strapi:latest
    build: ./orqa-image-grading-strapi
    ports:
      - "1337:1337"
    command: "npm run develop"  
    networks: 
      - orqa
    env_file: orqa-image-grading-strapi/.env
  db:
    image: mysql/mysql-server:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'orqa'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'S1956k1988'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    networks:
      - orqa
networks: 
  orqa: